services:
  yalp-db:
    image: postgres:latest
    container_name: yalp-db
    environment:
      POSTGRES_USER: yalp-db
      POSTGRES_PASSWORD: yalp-db_secret
      POSTGRES_DB: yalp-db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yalp-md

  yalp-md-redis:
    image: redis:latest
    container_name: yalp-md-redis
    ports:
      - "6378:6379"
    networks:
      - yalp-md
      
networks:
  yalp-md: 
    external: true

volumes:
  postgres_data: